'use strict';
// Dados do jogo: itens, receitas, construções, criaturas e civilizações.

const PLAYER_COLOR = '#e0a526';
const WORLD_SEED = 20261001; // mapa fixo: o mesmo mundo em todas as partidas

// Partes do equipamento
const EQUIP_SLOTS = [
  { key: 'weapon', name: 'Arma',       sub: 'Mão direita' },
  { key: 'tool',   name: 'Ferramenta', sub: 'Mão esquerda' },
  { key: 'tool2',  name: 'Ferramenta 2', sub: 'Na cintura (troca sozinha quando precisa)' },
  { key: 'head',   name: 'Elmo',       sub: 'Cabeça' },
  { key: 'torso',  name: 'Gibão',      sub: 'Torso' },
  { key: 'legs',   name: 'Calções',    sub: 'Pernas' },
  { key: 'feet',   name: 'Botas',      sub: 'Pés' },
  { key: 'shield', name: 'Escudo',     sub: 'Braço' },
];
const ARMOR_SLOTS = ['head', 'torso', 'legs', 'feet', 'shield'];
const TOOL_NAMES = { axe: 'Corte', pick: 'Mineração', rod: 'Pesca', hoe: 'Lavoura', water: 'Rega' };
const TIER_NAMES = ['Mãos', 'Pedra', 'Bronze', 'Ferro', 'Aço'];

const ITEMS = {
  // ------------------------------------------------ recursos brutos
  wood:        { name: 'Madeira',            icon: '🪵', cat: 'Recursos', price: 2 },
  hardwood:    { name: 'Madeira Nobre',      icon: '🌳', cat: 'Recursos', price: 12 },
  yew_wood:    { name: 'Madeira de Teixo',   icon: '🎋', cat: 'Recursos', price: 9 },
  spider_silk: { name: 'Seda de Aranha',     icon: '🕸️', cat: 'Recursos', price: 15 },
  resin:       { name: 'Resina de Pinho',    icon: '🍯', cat: 'Recursos', price: 4 },
  stone:       { name: 'Pedra',              icon: '🪨', cat: 'Recursos', price: 2 },
  clay:        { name: 'Argila',             icon: '🏺', cat: 'Recursos', price: 2 },
  coal:        { name: 'Carvão',             icon: '⚫', cat: 'Recursos', price: 4 },
  copper_ore:  { name: 'Minério de Cobre',   icon: '🟠', cat: 'Recursos', price: 5 },
  tin_ore:     { name: 'Minério de Estanho', icon: '⚪', cat: 'Recursos', price: 5 },
  iron_ore:    { name: 'Minério de Ferro',   icon: '🟤', cat: 'Recursos', price: 7 },
  silver_ore:  { name: 'Minério de Prata',   icon: '🔘', cat: 'Recursos', price: 16 },
  gold_ore:    { name: 'Pepita de Ouro',     icon: '🟡', cat: 'Recursos', price: 28 },
  gem:         { name: 'Gema Bruta',         icon: '💎', cat: 'Recursos', price: 60 },
  fiber:       { name: 'Fibra de Linho',     icon: '🧵', cat: 'Recursos', price: 1 },
  herb:        { name: 'Erva Medicinal',     icon: '🌿', cat: 'Recursos', price: 3 },
  leather:     { name: 'Couro',              icon: '🟫', cat: 'Recursos', price: 7 },
  wheat:       { name: 'Trigo',              icon: '🌾', cat: 'Recursos', price: 2 },
  barley:      { name: 'Cevada',             icon: '🌱', cat: 'Recursos', price: 3 },
  wool:        { name: 'Lã',                 icon: '🧶', cat: 'Recursos', price: 6 },
  honey:       { name: 'Mel',                icon: '🍯', cat: 'Recursos', price: 8 },
  wheat_seed:  { name: 'Sementes de Trigo',  icon: '🌰', cat: 'Sementes', price: 1, seed: 'wheat' },
  carrot_seed: { name: 'Sementes de Cenoura', icon: '🌰', cat: 'Sementes', price: 2, seed: 'carrot' },
  cabbage_seed:{ name: 'Sementes de Repolho', icon: '🌰', cat: 'Sementes', price: 2, seed: 'cabbage' },
  barley_seed: { name: 'Sementes de Cevada', icon: '🌰', cat: 'Sementes', price: 2, seed: 'barley' },
  spices:      { name: 'Especiarias',        icon: '🌶️', cat: 'Diversos', price: 25 },
  silk_cloth:  { name: 'Seda Fina',          icon: '🎀', cat: 'Diversos', price: 35 },
  bone:        { name: 'Osso',               icon: '🦴', cat: 'Recursos', price: 2 },
  wolf_pelt:   { name: 'Pele de Lobo',       icon: '🐺', cat: 'Recursos', price: 14 },
  deer_antler: { name: 'Chifre de Cervo',    icon: '🦌', cat: 'Recursos', price: 10 },
  boar_tusk:   { name: 'Presa de Javali',    icon: '🐗', cat: 'Recursos', price: 9 },
  // ------------------------------------------------ materiais trabalhados
  rope:        { name: 'Corda',              icon: '🪢', cat: 'Materiais', price: 4 },
  cloth:       { name: 'Tecido de Linho',    icon: '🧶', cat: 'Materiais', price: 6 },
  brick:       { name: 'Tijolo',             icon: '🧱', cat: 'Materiais', price: 4 },
  bronze_bar:  { name: 'Lingote de Bronze',  icon: '🥉', cat: 'Materiais', price: 14 },
  iron_bar:    { name: 'Barra de Ferro',     icon: '🔩', cat: 'Materiais', price: 18 },
  steel_bar:   { name: 'Lingote de Aço',     icon: '⚙️', cat: 'Materiais', price: 40 },
  silver_bar:  { name: 'Lingote de Prata',   icon: '🥈', cat: 'Materiais', price: 36 },
  gold_bar:    { name: 'Lingote de Ouro',    icon: '🥇', cat: 'Materiais', price: 60 },
  // ------------------------------------------------ comida e remédios
  berries:     { name: 'Frutas Silvestres',  icon: '🫐', cat: 'Comida', price: 1,  food: 10, heal: 3 },
  apple:       { name: 'Maçã',               icon: '🍎', cat: 'Comida', price: 2,  food: 10, heal: 3 },
  coconut:     { name: 'Coco',               icon: '🥥', cat: 'Comida', price: 3,  food: 14, heal: 5 },
  meat:        { name: 'Carne Crua',         icon: '🥩', cat: 'Comida', price: 3,  food: 12, heal: 0 },
  cooked_meat: { name: 'Carne Assada',       icon: '🍖', cat: 'Comida', price: 9,  food: 35, heal: 20 },
  bread:       { name: 'Pão',                icon: '🍞', cat: 'Comida', price: 7,  food: 30, heal: 12 },
  carrot:      { name: 'Cenoura',            icon: '🥕', cat: 'Comida', price: 2,  food: 8,  heal: 2 },
  cabbage:     { name: 'Repolho',            icon: '🥬', cat: 'Comida', price: 3,  food: 10, heal: 2 },
  egg:         { name: 'Ovo',                icon: '🥚', cat: 'Comida', price: 3,  food: 6,  heal: 1 },
  milk:        { name: 'Leite',              icon: '🥛', cat: 'Comida', price: 4,  food: 8,  heal: 3 },
  ram:         { name: 'Aríete',             icon: '🪵', cat: 'Diversos', price: 120, siege: 'ram' },
  catapult:    { name: 'Catapulta',          icon: '🏹', cat: 'Diversos', price: 200, siege: 'catapult' },
  stew:        { name: 'Ensopado',           icon: '🍲', cat: 'Comida', price: 26, food: 55, heal: 30, buff: 'str' },
  veg_soup:    { name: 'Sopa de Legumes',    icon: '🥣', cat: 'Comida', price: 16, food: 35, heal: 15, buff: 'def' },
  omelette:    { name: 'Omelete',            icon: '🍳', cat: 'Comida', price: 14, food: 30, heal: 10, buff: 'vigor' },
  meat_pie:    { name: 'Torta de Carne',     icon: '🥧', cat: 'Comida', price: 30, food: 60, heal: 25, buff: 'regen' },
  honey_cake:  { name: 'Bolo de Mel',        icon: '🍰', cat: 'Comida', price: 32, food: 45, heal: 15, buff: 'wisdom' },
  beer:        { name: 'Cerveja',            icon: '🍺', cat: 'Comida', price: 12, food: 5,  heal: 5,  buff: 'courage' },
  mead:        { name: 'Hidromel',           icon: '🍶', cat: 'Comida', price: 22, food: 5,  heal: 20, buff: 'mead' },
  wine:        { name: 'Vinho',              icon: '🍷', cat: 'Comida', price: 30, food: 5,  heal: 10, buff: 'charm' },
  apple_pie:   { name: 'Torta de Maçã',      icon: '🥧', cat: 'Comida', price: 16, food: 50, heal: 20 },
  trout:       { name: 'Truta',              icon: '🐟', cat: 'Comida', price: 5,  food: 9,  heal: 0, fish: true },
  carp:        { name: 'Carpa',              icon: '🐟', cat: 'Comida', price: 4,  food: 9,  heal: 0, fish: true },
  sardine:     { name: 'Sardinha',           icon: '🐟', cat: 'Comida', price: 4,  food: 7,  heal: 0, fish: true },
  cod:         { name: 'Bacalhau',           icon: '🐟', cat: 'Comida', price: 9,  food: 12, heal: 0, fish: true },
  goldfish:    { name: 'Peixe-Dourado',      icon: '🐠', cat: 'Diversos', price: 45 },
  old_boot:    { name: 'Bota Velha',         icon: '🥾', cat: 'Diversos', price: 1 },
  silver_ring: { name: 'Anel de Prata',      icon: '💍', cat: 'Diversos', price: 90 },
  ancient_coin:{ name: 'Moeda Antiga',       icon: '🪙', cat: 'Diversos', price: 40 },
  dragon_scale:{ name: 'Escama de Dragão',   icon: '🐉', cat: 'Diversos', price: 150 },
  arrow:       { name: 'Flecha',             icon: '➶',  cat: 'Armas', price: 1, ammo: true, adm: 0 },
  iron_arrow:  { name: 'Flecha de Ferro',    icon: '🏹', cat: 'Armas', price: 3, ammo: true, adm: 7 },
  cooked_fish: { name: 'Peixe Assado',       icon: '🍤', cat: 'Comida', price: 10, food: 30, heal: 16 },
  herbal_salve:{ name: 'Unguento de Ervas',  icon: '🧴', cat: 'Comida', price: 14, food: 0,  heal: 45 },
  // ------------------------------------------------ ferramentas
  stone_axe:   { name: 'Machado de Pedra',   icon: '🪓', cat: 'Ferramentas', price: 10,  slot: 'tool', tool: 'axe',  tier: 1, power: 2 },
  bronze_axe:  { name: 'Machado de Bronze',  icon: '🪓', cat: 'Ferramentas', price: 35,  slot: 'tool', tool: 'axe',  tier: 2, power: 3 },
  iron_axe:    { name: 'Machado de Ferro',   icon: '🪓', cat: 'Ferramentas', price: 60,  slot: 'tool', tool: 'axe',  tier: 3, power: 4 },
  steel_axe:   { name: 'Machado de Aço',     icon: '🪓', cat: 'Ferramentas', price: 130, slot: 'tool', tool: 'axe',  tier: 4, power: 5 },
  stone_pick:  { name: 'Picareta de Pedra',  icon: '⛏️', cat: 'Ferramentas', price: 12,  slot: 'tool', tool: 'pick', tier: 1, power: 2 },
  bronze_pick: { name: 'Picareta de Bronze', icon: '⛏️', cat: 'Ferramentas', price: 40,  slot: 'tool', tool: 'pick', tier: 2, power: 3 },
  iron_pick:   { name: 'Picareta de Ferro',  icon: '⛏️', cat: 'Ferramentas', price: 70,  slot: 'tool', tool: 'pick', tier: 3, power: 4 },
  steel_pick:  { name: 'Picareta de Aço',    icon: '⛏️', cat: 'Ferramentas', price: 150, slot: 'tool', tool: 'pick', tier: 4, power: 5 },
  hoe:         { name: 'Enxada',             icon: '⛏️', cat: 'Ferramentas', price: 10, slot: 'tool', tool: 'hoe', tier: 1, power: 1 },
  watering_can:{ name: 'Regador',            icon: '🪣', cat: 'Ferramentas', price: 22, slot: 'tool', tool: 'water', tier: 1, power: 1 },
  wood_shield: { name: 'Escudo de Madeira',  icon: '🛡️', cat: 'Armaduras', price: 20,  slot: 'shield', def: 1, block: 0.45, color: '#8b5a2b' },
  iron_shield: { name: 'Escudo de Ferro',    icon: '🛡️', cat: 'Armaduras', price: 90,  slot: 'shield', def: 2, block: 0.62, color: '#9aa0a8' },
  steel_shield:{ name: 'Escudo de Aço',      icon: '🛡️', cat: 'Armaduras', price: 200, slot: 'shield', def: 3, block: 0.78, color: '#d9dee3' },
  wool_cloak:  { name: 'Manto de Lã',        icon: '🧥', cat: 'Armaduras', price: 40,  slot: 'torso', def: 2, color: '#e8e0cc' },
  fishing_rod: { name: 'Vara de Pesca',      icon: '🎣', cat: 'Ferramentas', price: 12,  slot: 'tool', tool: 'rod',  tier: 1, power: 1 },
  boat:        { name: 'Barco a Remo',       icon: '🛶', cat: 'Ferramentas', price: 160 },
  // ------------------------------------------------ armas
  club:        { name: 'Porrete de Madeira', icon: '🏏', cat: 'Armas', price: 8,   slot: 'weapon', dmg: 8,  color: '#8b5a2b', len: 16 },
  short_bow:   { name: 'Arco Curto',         icon: '🏹', cat: 'Armas', price: 30,  slot: 'weapon', dmg: 10, ranged: true, color: '#8b5a2b', len: 14 },
  yew_bow:     { name: 'Arco Longo de Teixo', icon: '🏹', cat: 'Armas', price: 120, slot: 'weapon', dmg: 18, ranged: true, color: '#5a3a1a', len: 16 },
  ancient_blade:{ name: 'Lâmina Ancestral',  icon: '🗡️', cat: 'Armas', price: 600, slot: 'weapon', dmg: 40, color: '#8ef0ff', len: 27 },
  troll_club:  { name: 'Clava do Troll',     icon: '🏏', cat: 'Armas', price: 380, slot: 'weapon', dmg: 33, color: '#6a7a4a', len: 24 },
  bone_knife:  { name: 'Faca de Osso',       icon: '🔪', cat: 'Armas', price: 12,  slot: 'weapon', dmg: 10, color: '#e8e0c8', len: 12 },
  stone_spear: { name: 'Lança de Pedra',     icon: '🔱', cat: 'Armas', price: 18,  slot: 'weapon', dmg: 11, color: '#9a8a70', len: 26 },
  battle_axe:  { name: 'Machadinha de Batalha', icon: '🪓', cat: 'Armas', price: 25, slot: 'weapon', dmg: 13, color: '#9a9a9a', len: 18 },
  bronze_sword:{ name: 'Espada de Bronze',   icon: '🗡️', cat: 'Armas', price: 70,  slot: 'weapon', dmg: 16, color: '#cd8a4a', len: 21 },
  iron_sword:  { name: 'Espada de Ferro',    icon: '🗡️', cat: 'Armas', price: 110, slot: 'weapon', dmg: 20, color: '#cfd6dd', len: 22 },
  war_axe:     { name: 'Machado de Guerra',  icon: '🪓', cat: 'Armas', price: 140, slot: 'weapon', dmg: 23, color: '#b0b6bd', len: 22 },
  steel_sword: { name: 'Espada de Aço',      icon: '⚔️', cat: 'Armas', price: 220, slot: 'weapon', dmg: 27, color: '#e8eef4', len: 24 },
  silver_sword:{ name: 'Espada de Prata',    icon: '⚔️', cat: 'Armas', price: 280, slot: 'weapon', dmg: 29, color: '#f4f8ff', len: 24 },
  royal_sword: { name: 'Espada Real',        icon: '⚔️', cat: 'Armas', price: 420, slot: 'weapon', dmg: 34, color: '#ffd54a', len: 26 },
  // ------------------------------------------------ armaduras (elmo, gibão, calções, botas)
  linen_hood:     { name: 'Capuz de Linho',     icon: '🧢', cat: 'Armaduras', price: 12,  slot: 'head',  def: 1, color: '#cfc4a4' },
  leather_cap:    { name: 'Capuz de Couro',     icon: '🧢', cat: 'Armaduras', price: 22,  slot: 'head',  def: 1, color: '#7a4a24' },
  bronze_helm:    { name: 'Elmo de Bronze',     icon: '🪖', cat: 'Armaduras', price: 55,  slot: 'head',  def: 2, color: '#c08040' },
  iron_helm:      { name: 'Elmo de Ferro',      icon: '🪖', cat: 'Armaduras', price: 80,  slot: 'head',  def: 3, color: '#8d949c' },
  steel_helm:     { name: 'Elmo de Aço',        icon: '🪖', cat: 'Armaduras', price: 170, slot: 'head',  def: 4, color: '#d9dee3' },
  antler_helm:    { name: 'Elmo de Chifres',    icon: '🦌', cat: 'Armaduras', price: 45,  slot: 'head',  def: 2, color: '#8a6a4a' },
  silk_hood:      { name: 'Capuz de Seda',      icon: '🧢', cat: 'Armaduras', price: 90,  slot: 'head',  def: 3, color: '#e8e4f0' },
  crystal_crown:  { name: 'Coroa de Cristal',   icon: '👑', cat: 'Armaduras', price: 650, slot: 'head',  def: 7, color: '#9ef0ff' },
  dragon_mail:    { name: 'Couraça de Escamas de Dragão', icon: '🛡️', cat: 'Armaduras', price: 900, slot: 'torso', def: 12, color: '#b0302a' },
  royal_helm:     { name: 'Elmo Real',          icon: '👑', cat: 'Armaduras', price: 400, slot: 'head',  def: 6, color: '#ffd54a' },
  linen_tunic:    { name: 'Túnica de Linho',    icon: '👕', cat: 'Armaduras', price: 20,  slot: 'torso', def: 1, color: '#d8cfb4' },
  wolf_cloak:     { name: 'Manto de Pele de Lobo', icon: '🧥', cat: 'Armaduras', price: 90, slot: 'torso', def: 4, color: '#8d8f96' },
  leather_jerkin: { name: 'Gibão de Couro',     icon: '🦺', cat: 'Armaduras', price: 45,  slot: 'torso', def: 3, color: '#7a4a24' },
  bronze_cuirass: { name: 'Couraça de Bronze',  icon: '🛡️', cat: 'Armaduras', price: 120, slot: 'torso', def: 4, color: '#c08040' },
  chainmail:      { name: 'Cota de Malha',      icon: '🛡️', cat: 'Armaduras', price: 170, slot: 'torso', def: 6, color: '#8d949c' },
  plate_armor:    { name: 'Armadura de Placas', icon: '🛡️', cat: 'Armaduras', price: 380, slot: 'torso', def: 8, color: '#d9dee3' },
  linen_pants:    { name: 'Calções de Linho',   icon: '👖', cat: 'Armaduras', price: 16,  slot: 'legs',  def: 1, color: '#b8ad90' },
  leather_breeches:{ name: 'Calções de Couro',  icon: '👖', cat: 'Armaduras', price: 32,  slot: 'legs',  def: 2, color: '#5e3a1c' },
  bronze_greaves: { name: 'Grevas de Bronze',   icon: '👖', cat: 'Armaduras', price: 85,  slot: 'legs',  def: 3, color: '#b07438' },
  iron_greaves:   { name: 'Grevas de Ferro',    icon: '👖', cat: 'Armaduras', price: 120, slot: 'legs',  def: 4, color: '#7d848c' },
  steel_greaves:  { name: 'Grevas de Aço',      icon: '👖', cat: 'Armaduras', price: 260, slot: 'legs',  def: 5, color: '#c9ced3' },
  leather_boots:  { name: 'Botas de Couro',     icon: '🥾', cat: 'Armaduras', price: 24,  slot: 'feet',  def: 1, color: '#4a2e16' },
  bronze_boots:   { name: 'Botas de Bronze',    icon: '👢', cat: 'Armaduras', price: 60,  slot: 'feet',  def: 2, color: '#a86c30' },
  iron_boots:     { name: 'Botas de Ferro',     icon: '👢', cat: 'Armaduras', price: 85,  slot: 'feet',  def: 2, color: '#6d747c' },
  steel_sabatons: { name: 'Escarpes de Aço',    icon: '👢', cat: 'Armaduras', price: 170, slot: 'feet',  def: 3, color: '#b9bec3' },
  // animais novos (raposa, coelho, cabra montesa e urso) e o que se faz com eles
  fox_pelt:     { name: 'Pele de Raposa',     icon: '🦊', cat: 'Recursos', price: 18 },
  rabbit_hide:  { name: 'Pele de Coelho',     icon: '🐇', cat: 'Recursos', price: 6 },
  goat_horn:    { name: 'Chifre de Cabra',    icon: '📯', cat: 'Recursos', price: 12 },
  bear_pelt:    { name: 'Pele de Urso',       icon: '🐻', cat: 'Recursos', price: 45 },
  bear_claw:    { name: 'Garra de Urso',      icon: '🐾', cat: 'Recursos', price: 20 },
  hard_leather: { name: 'Couro Curtido',      icon: '🟫', cat: 'Materiais', price: 16 },
  iron_spear:   { name: 'Lança de Ferro',     icon: '🔱', cat: 'Armas', price: 70,  slot: 'weapon', dmg: 16, color: '#8d949c', len: 28 },
  iron_mace:    { name: 'Maça de Ferro',      icon: '🔨', cat: 'Armas', price: 90,  slot: 'weapon', dmg: 19, color: '#7d848c', len: 16 },
  horn_bow:     { name: 'Arco Composto de Chifre', icon: '🏹', cat: 'Armas', price: 160, slot: 'weapon', dmg: 22, ranged: true, color: '#d8c8a0', len: 15 },
  bear_claws:   { name: 'Garras de Urso',     icon: '🐾', cat: 'Armas', price: 85,  slot: 'weapon', dmg: 15, color: '#e6dcc4', len: 10 },
  fox_hood:     { name: 'Capuz de Raposa',    icon: '🦊', cat: 'Armaduras', price: 55, slot: 'head',  def: 2, color: '#d0682a' },
  rabbit_boots: { name: 'Botas Forradas de Coelho', icon: '🥾', cat: 'Armaduras', price: 30, slot: 'feet', def: 2, color: '#e0d4bc' },
  hard_jerkin:  { name: 'Gibão de Couro Curtido', icon: '🦺', cat: 'Armaduras', price: 95, slot: 'torso', def: 5, color: '#5e3416' },
  bear_coat:    { name: 'Casaco de Pele de Urso', icon: '🐻', cat: 'Armaduras', price: 150, slot: 'torso', def: 6, color: '#5a3a22' },
};

// Grupos usados em receitas ("qualquer peixe")
const ITEM_GROUPS = { fish: ['trout', 'carp', 'sardine', 'cod'] };
const GROUP_INFO = { fish: { name: 'Qualquer Peixe', icon: '🐟' } };

// station: null = feito à mão; 'fogueira' (fogueira, cabana, casa ou casarão), 'bancada', 'forja'
const RECIPES = [
  // à mão
  { out: 'stone_axe',     n: 1, cost: { wood: 3, stone: 3 },                    station: null },
  { out: 'stone_pick',    n: 1, cost: { wood: 3, stone: 4 },                    station: null },
  { out: 'club',          n: 1, cost: { wood: 6 },                              station: null },
  { out: 'rope',          n: 1, cost: { fiber: 3 },                             station: null },
  { out: 'fishing_rod',   n: 1, cost: { wood: 3, rope: 1 },                     station: null },
  { out: 'stone_spear',   n: 1, cost: { wood: 4, stone: 3, rope: 1 },           station: null },
  { out: 'hoe',           n: 1, cost: { wood: 3, stone: 2 },                    station: null },
  { out: 'bone_knife',    n: 1, cost: { bone: 3, wood: 1, rope: 1 },            station: null },
  { out: 'arrow',         n: 6, cost: { wood: 1, stone: 1 },                    station: null },
  { out: 'short_bow',     n: 1, cost: { wood: 4, rope: 2 },                     station: 'bancada' },
  { out: 'yew_bow',       n: 1, cost: { yew_wood: 4, rope: 2, resin: 1 },       station: 'bancada' },
  { out: 'silk_hood',     n: 1, cost: { spider_silk: 4, cloth: 1 },             station: 'bancada' },
  // fogueira
  { out: 'cooked_meat',   n: 1, cost: { meat: 1, wood: 1 },                     station: 'fogueira' },
  { out: 'cooked_fish',   n: 1, cost: { fish: 1, wood: 1 },                     station: 'fogueira' },
  { out: 'bread',         n: 1, cost: { wheat: 3 },                             station: 'fogueira' },
  { out: 'apple_pie',     n: 1, cost: { apple: 3, wheat: 2 },                   station: 'fogueira' },
  { out: 'herbal_salve',  n: 1, cost: { herb: 3, resin: 1 },                    station: 'fogueira' },
  { out: 'veg_soup',      n: 1, cost: { carrot: 2, cabbage: 1 },                station: 'fogueira' },
  { out: 'omelette',      n: 1, cost: { egg: 2, milk: 1 },                      station: 'fogueira' },
  { out: 'stew',          n: 1, cost: { meat: 1, carrot: 2, cabbage: 1 },       station: 'cozinha' },
  { out: 'meat_pie',      n: 1, cost: { meat: 2, wheat: 2, egg: 1 },            station: 'cozinha' },
  { out: 'honey_cake',    n: 1, cost: { wheat: 2, egg: 2, milk: 1, honey: 1 },  station: 'cozinha' },
  { out: 'beer',          n: 2, cost: { barley: 3, wheat: 1 },                  station: 'cervejaria' },
  { out: 'mead',          n: 2, cost: { honey: 3 },                             station: 'cervejaria' },
  // bancada
  { out: 'cloth',         n: 1, cost: { fiber: 4 },                             station: 'bancada' },
  { out: 'battle_axe',    n: 1, cost: { wood: 5, stone: 8 },                    station: 'bancada' },
  { out: 'linen_hood',    n: 1, cost: { cloth: 2 },                             station: 'bancada' },
  { out: 'linen_tunic',   n: 1, cost: { cloth: 4 },                             station: 'bancada' },
  { out: 'linen_pants',   n: 1, cost: { cloth: 3 },                             station: 'bancada' },
  { out: 'leather_cap',   n: 1, cost: { leather: 3 },                           station: 'bancada' },
  { out: 'leather_jerkin',n: 1, cost: { leather: 6, cloth: 1 },                 station: 'bancada' },
  { out: 'leather_breeches', n: 1, cost: { leather: 4 },                        station: 'bancada' },
  { out: 'leather_boots', n: 1, cost: { leather: 3 },                           station: 'bancada' },
  { out: 'hard_leather',  n: 1, cost: { leather: 2, resin: 1 },                 station: 'bancada' },
  { out: 'fox_hood',      n: 1, cost: { fox_pelt: 2, cloth: 1 },                station: 'bancada' },
  { out: 'rabbit_boots',  n: 1, cost: { rabbit_hide: 3, leather: 1 },           station: 'bancada' },
  { out: 'hard_jerkin',   n: 1, cost: { hard_leather: 4, rope: 1 },             station: 'bancada' },
  { out: 'bear_coat',     n: 1, cost: { bear_pelt: 2, leather: 2, rope: 1 },    station: 'bancada' },
  { out: 'horn_bow',      n: 1, cost: { yew_wood: 2, goat_horn: 2, rope: 2, resin: 1 }, station: 'bancada' },
  { out: 'bear_claws',    n: 1, cost: { bear_claw: 3, hard_leather: 1 },        station: 'bancada' },
  { out: 'boat',          n: 1, cost: { wood: 40, rope: 4, resin: 3 },          station: 'bancada' },
  { out: 'ram',           n: 1, cost: { wood: 30, iron_bar: 4, rope: 4 },       station: 'bancada' },
  { out: 'catapult',      n: 1, cost: { wood: 40, stone: 20, iron_bar: 6, rope: 6 }, station: 'bancada' },
  { out: 'wood_shield',   n: 1, cost: { wood: 6, leather: 1 },                  station: 'bancada' },
  { out: 'wool_cloak',    n: 1, cost: { wool: 5, cloth: 1 },                    station: 'bancada' },
  { out: 'antler_helm',   n: 1, cost: { deer_antler: 2, leather: 2 },           station: 'bancada' },
  { out: 'wolf_cloak',    n: 1, cost: { wolf_pelt: 3, leather: 2 },             station: 'bancada' },
  // forja: fundição
  { out: 'brick',         n: 2, cost: { clay: 3, coal: 1 },                     station: 'forja' },
  { out: 'bronze_bar',    n: 1, cost: { copper_ore: 2, tin_ore: 1, coal: 1 },   station: 'forja' },
  { out: 'iron_bar',      n: 1, cost: { iron_ore: 2, coal: 1 },                 station: 'forja' },
  { out: 'steel_bar',     n: 1, cost: { iron_bar: 2, coal: 2 },                 station: 'forja' },
  { out: 'silver_bar',    n: 1, cost: { silver_ore: 2, coal: 1 },               station: 'forja' },
  { out: 'gold_bar',      n: 1, cost: { gold_ore: 2, coal: 1 },                 station: 'forja' },
  // forja: ferramentas
  { out: 'bronze_axe',    n: 1, cost: { wood: 2, bronze_bar: 3 },               station: 'forja' },
  { out: 'bronze_pick',   n: 1, cost: { wood: 2, bronze_bar: 4 },               station: 'forja' },
  { out: 'iron_axe',      n: 1, cost: { wood: 3, iron_bar: 3 },                 station: 'forja' },
  { out: 'iron_pick',     n: 1, cost: { wood: 3, iron_bar: 4 },                 station: 'forja' },
  { out: 'steel_axe',     n: 1, cost: { hardwood: 2, steel_bar: 3 },            station: 'forja' },
  { out: 'steel_pick',    n: 1, cost: { hardwood: 2, steel_bar: 4 },            station: 'forja' },
  // forja: armas
  { out: 'bronze_sword',  n: 1, cost: { wood: 1, bronze_bar: 5 },               station: 'forja' },
  { out: 'iron_sword',    n: 1, cost: { wood: 2, iron_bar: 6 },                 station: 'forja' },
  { out: 'iron_spear',    n: 1, cost: { hardwood: 2, iron_bar: 3 },             station: 'forja' },
  { out: 'iron_mace',     n: 1, cost: { hardwood: 1, iron_bar: 5 },             station: 'forja' },
  { out: 'war_axe',       n: 1, cost: { hardwood: 2, iron_bar: 7 },             station: 'forja' },
  { out: 'steel_sword',   n: 1, cost: { hardwood: 1, steel_bar: 6 },            station: 'forja' },
  { out: 'silver_sword',  n: 1, cost: { steel_bar: 3, silver_bar: 4 },          station: 'forja' },
  { out: 'royal_sword',   n: 1, cost: { steel_bar: 6, gold_bar: 3, gem: 2 },    station: 'forja' },
  // forja: armaduras
  { out: 'bronze_helm',   n: 1, cost: { bronze_bar: 3 },                        station: 'forja' },
  { out: 'bronze_cuirass',n: 1, cost: { bronze_bar: 7, leather: 2 },            station: 'forja' },
  { out: 'bronze_greaves',n: 1, cost: { bronze_bar: 5 },                        station: 'forja' },
  { out: 'bronze_boots',  n: 1, cost: { bronze_bar: 3, leather: 1 },            station: 'forja' },
  { out: 'iron_helm',     n: 1, cost: { iron_bar: 4 },                          station: 'forja' },
  { out: 'chainmail',     n: 1, cost: { iron_bar: 8, leather: 3 },              station: 'forja' },
  { out: 'iron_greaves',  n: 1, cost: { iron_bar: 6 },                          station: 'forja' },
  { out: 'iron_boots',    n: 1, cost: { iron_bar: 3, leather: 2 },              station: 'forja' },
  { out: 'steel_helm',    n: 1, cost: { steel_bar: 4 },                         station: 'forja' },
  { out: 'plate_armor',   n: 1, cost: { steel_bar: 9, leather: 3 },             station: 'forja' },
  { out: 'steel_greaves', n: 1, cost: { steel_bar: 6 },                         station: 'forja' },
  { out: 'steel_sabatons',n: 1, cost: { steel_bar: 3, leather: 2 },             station: 'forja' },
  { out: 'royal_helm',    n: 1, cost: { steel_bar: 3, gold_bar: 3, gem: 1 },    station: 'forja' },
  { out: 'silver_ring',   n: 1, cost: { silver_bar: 1 },                        station: 'forja' },
  { out: 'iron_arrow',    n: 10, cost: { wood: 2, iron_bar: 1 },                station: 'forja' },
  { out: 'watering_can',  n: 1, cost: { wood: 2, iron_bar: 1 },                 station: 'forja' },
  { out: 'iron_shield',   n: 1, cost: { iron_bar: 4, wood: 2 },                 station: 'forja' },
  { out: 'steel_shield',  n: 1, cost: { steel_bar: 4, leather: 2 },             station: 'forja' },
  { out: 'dragon_mail',   n: 1, cost: { dragon_scale: 6, steel_bar: 4, leather: 4 }, station: 'forja' },
];

const STATIONS = {
  fogueira: { name: 'Fogueira / Cabana / Casa', types: ['campfire', 'cabin', 'house', 'manor'] },
  bancada:  { name: 'Bancada de Trabalho',      types: ['workbench'] },
  forja:    { name: 'Forja',                    types: ['forge'] },
  cozinha:  { name: 'Forno a Lenha',            types: ['oven'] },
  cervejaria: { name: 'Cervejaria',            types: ['brewery'] },
};

// Construções do jogador
const BUILDINGS = {
  cabin:      { name: 'Cabana',          w: 2, h: 2, blocks: true,  cost: { wood: 25, stone: 5 },  desc: 'Salve o jogo, durma e cozinhe. Vira seu ponto de retorno.' },
  campfire:   { name: 'Fogueira',        w: 1, h: 1, blocks: true,  cost: { wood: 5, stone: 3 },   desc: 'Cozinhe carne, peixe e asse pão. Ilumina a noite.' },
  workbench:  { name: 'Bancada',         w: 2, h: 1, blocks: true,  cost: { wood: 15, stone: 2 },  desc: 'Tecidos, roupas de linho e couro, machadinhas e barcos.' },
  forge:      { name: 'Forja',           w: 2, h: 2, blocks: true,  cost: { stone: 25, wood: 10, clay: 6 }, desc: 'Funda metais e forje ferramentas, armas e armaduras.' },
  house:      { name: 'Casa',            w: 2, h: 2, blocks: true,  cost: { wood: 30, stone: 15 }, desc: '+2 seguidores. Também serve para salvar e descansar.' },
  pcastle:    { name: 'Castelo',         w: 7, h: 7, blocks: true,  cost: { stone: 250, wood: 150, brick: 60, iron_bar: 25 }, desc: 'Transforma a sua vila livre num reino seu: castelo, guarnição, território e o título de rei. A vila precisa ter crescido até o nível 3, e o castelo fica perto dela. Custa também 3000 🪙. Só um reino fundado por vez (se ele cair, dá para fundar outro).' },
  manor:      { name: 'Casarão',         w: 3, h: 3, blocks: true,  cost: { brick: 30, wood: 20, hardwood: 5 }, desc: '+4 seguidores. Casa de tijolos para salvar e descansar.' },
  farm:       { name: 'Fazenda',         w: 3, h: 3, blocks: false, cost: { wood: 15 },            desc: 'Produz 6 de trigo todo amanhecer.' },
  barracks:   { name: 'Quartel',         w: 3, h: 3, blocks: true,  cost: { wood: 40, stone: 30, iron_bar: 4 }, desc: '+4 seguidores. Treine soldados mais baratos.' },
  oven:       { name: 'Forno a Lenha',   w: 2, h: 1, blocks: true,  cost: { stone: 14, clay: 6 },  desc: 'Cozinha pratos especiais: ensopado, torta de carne e bolo de mel.' },
  brewery:    { name: 'Cervejaria',      w: 2, h: 2, blocks: true,  cost: { wood: 25, iron_bar: 2, rope: 2 }, desc: 'Fabrica cerveja (cevada) e hidromel (mel).' },
  coop:       { name: 'Galinheiro',      w: 2, h: 2, blocks: true,  cost: { wood: 20, fiber: 4 },  desc: 'Abriga até 6 galinhas, que botam ovos todo dia.' },
  pen:        { name: 'Curral',          w: 3, h: 3, blocks: false, cost: { wood: 30, stone: 6 },  desc: 'Cria até 3 vacas (leite) e 4 ovelhas (lã).' },
  beehive:    { name: 'Colmeia',         w: 1, h: 1, blocks: true,  cost: { wood: 6, resin: 2 },   desc: 'Produz mel todo dia (menos no inverno).' },
  ptavern:    { name: 'Sua Taverna',     w: 3, h: 2, blocks: true,  cost: { wood: 40, stone: 20, brick: 8 }, desc: 'Vende sua comida e bebida todo dia e dá lucro. Melhor dentro de um reino.' },
  chest:      { name: 'Baú',             w: 1, h: 1, blocks: true,  cost: { wood: 12, iron_bar: 1 }, desc: 'Guarda itens fora da mochila. Cada baú tem o seu conteúdo.' },
  stable:     { name: 'Estábulo',        w: 3, h: 2, blocks: true,  cost: { wood: 35, stone: 10, rope: 4 }, desc: 'Abriga seu cavalo e permite comprar cavalos e carroças.' },
  biz_farm:   { name: 'Fazenda Comercial', w: 3, h: 2, blocks: false, cost: { wood: 30, stone: 8 },  desc: 'Empreendimento: contrate até 4 lavradores. Produz trigo e cevada todo dia (metade no inverno).' },
  biz_mill:   { name: 'Moinho',          w: 2, h: 2, blocks: true,  cost: { wood: 35, stone: 15, rope: 4 }, desc: 'Empreendimento: até 2 moleiros. Produz pão todo dia.' },
  biz_lumber: { name: 'Serraria',        w: 2, h: 2, blocks: true,  cost: { wood: 30, stone: 10, iron_bar: 2 }, desc: 'Empreendimento: até 3 madeireiros. Produz madeira e madeira de lei.' },
  biz_quarry: { name: 'Pedreira Própria', w: 2, h: 2, blocks: true, cost: { wood: 25, stone: 20 },  desc: 'Empreendimento: até 3 pedreiros. Produz pedra e argila.' },
  biz_mine:   { name: 'Mina',            w: 2, h: 2, blocks: true,  cost: { wood: 40, stone: 30, iron_bar: 4 }, desc: 'Empreendimento: até 3 mineiros. Produz carvão e minérios de ferro, cobre e estanho.' },
  biz_smithy: { name: 'Ferraria',        w: 2, h: 2, blocks: true,  cost: { stone: 30, wood: 15, iron_bar: 6, clay: 6 }, desc: 'Empreendimento: até 2 ferreiros. Produz barras de ferro e bronze.' },
  biz_shop:   { name: 'Empório',         w: 3, h: 2, blocks: true,  cost: { wood: 40, stone: 15, cloth: 6 }, desc: 'Empreendimento: até 3 comerciantes. Rende ouro todo dia (mais dentro de um reino).' },
  wall_wood:  { name: 'Paliçada',        w: 1, h: 1, blocks: true,  cost: { wood: 3 },             desc: 'Muro de madeira para proteger sua base.' },
  wall_stone: { name: 'Muro de Pedra',   w: 1, h: 1, blocks: true,  cost: { stone: 1 },            desc: 'Muro resistente de pedra.' },
};

// Construções das civilizações
const CIV_STRUCTS = {
  castle: { name: 'Castelo',  blocks: true },
  chapel: { name: 'Capela',   blocks: true },
  cathedral: { name: 'Catedral', blocks: true },
  shrine: { name: 'Santuário', blocks: true },
  arena:  { name: 'Arena',    blocks: false },
  vhouse: { name: 'Casa',     blocks: true },
  vbuild: { name: 'Casa em obras', blocks: true },
  store:  { name: 'Armazém',  blocks: true },
  smith:  { name: 'Ferreiro', blocks: true },
  lumber: { name: 'Madeireira', blocks: true },
  quarry: { name: 'Pedreira', blocks: true },
  tavern: { name: 'Taverna',  blocks: true },
  field:  { name: 'Plantação', blocks: false },
  camp:   { name: 'Acampamento de Bandidos', blocks: false },
  cave:   { name: 'Entrada de Caverna', blocks: false },
  well:   { name: 'Poço', blocks: true },
  vwall:  { name: 'Muralha', blocks: true },
  cave_exit: { name: 'Saída da Caverna', blocks: false },
  tchest: { name: 'Baú de Tesouro', blocks: true },
  dig:    { name: 'Tesouro Enterrado', blocks: false },
  // empreendimentos das famílias
  fmill:  { name: 'Moinho',  blocks: true },
  fshop:  { name: 'Empório', blocks: true },
  fforge: { name: 'Oficina', blocks: true },
  ffarm:  { name: 'Quinta',  blocks: false },
  fvine:  { name: 'Vinhedo', blocks: false },
};

const CREATURES = {
  fox:      { name: 'Raposa',   hp: 14,  dmg: 0,  speed: 95,  r: 9,  faction: 'prey',   drops: { fox_pelt: [1, 1], meat: [0, 1] }, xp: 5 },
  rabbit:   { name: 'Coelho',   hp: 6,   dmg: 0,  speed: 90,  r: 7,  faction: 'prey',   drops: { rabbit_hide: [1, 1], meat: [0, 1] }, xp: 2 },
  goat:     { name: 'Cabra Montesa', hp: 24, dmg: 0, speed: 85, r: 10, faction: 'prey', drops: { goat_horn: [0, 1], meat: [1, 2], leather: [0, 1] }, xp: 6 },
  bear:     { name: 'Urso',     hp: 110, dmg: 15, speed: 70,  r: 14, faction: 'wild',   drops: { bear_pelt: [1, 1], bear_claw: [1, 2], meat: [2, 4], bone: [1, 2] }, xp: 35, aggro: 5 },
  deer:     { name: 'Cervo',    hp: 20,  dmg: 0,  speed: 85,  r: 10, faction: 'prey',   drops: { meat: [1, 2], leather: [1, 1], bone: [0, 1], deer_antler: [0, 1] }, xp: 4 },
  boar:     { name: 'Javali',   hp: 38,  dmg: 6,  speed: 75,  r: 11, faction: 'prey',   drops: { meat: [2, 3], leather: [1, 1], bone: [1, 1], boar_tusk: [0, 1] }, xp: 9, aggro: 6 },
  wolf:     { name: 'Lobo',     hp: 32,  dmg: 7,  speed: 100, r: 10, faction: 'wild',   drops: { wolf_pelt: [1, 1], bone: [0, 1], meat: [1, 1] }, xp: 12, aggro: 7 },
  champion: { name: 'Campeão',  hp: 100, dmg: 10, speed: 92,  r: 11, faction: 'arena',  xp: 30, aggro: 14 },
  ram_e:    { name: 'Aríete',   hp: 260, dmg: 0,  speed: 34,  r: 16, faction: 'engine', xp: 0 },
  catapult_e: { name: 'Catapulta', hp: 180, dmg: 0, speed: 0, r: 16, faction: 'engine', xp: 0 },
  bandit:   { name: 'Bandido',  hp: 55,  dmg: 10, speed: 82,  r: 10, faction: 'bandit', gold: [8, 25],   xp: 20, aggro: 8 },
  guard:    { name: 'Guarda',   hp: 70,  dmg: 11, speed: 88,  r: 10, faction: 'civ',    gold: [4, 12],   xp: 25, aggro: 9 },
  rebel:    { name: 'Rebelde',  hp: 62,  dmg: 10, speed: 86,  r: 10, faction: 'rebel',  gold: [5, 15],   xp: 22, aggro: 9 },
  lord:     { name: 'Soberano', hp: 320, dmg: 18, speed: 80,  r: 13, faction: 'civ',    gold: [150, 250], xp: 200, aggro: 14 },
  villager: { name: 'Aldeão',   hp: 40,  dmg: 6,  speed: 40,  r: 9,  faction: 'civ',    xp: 6, aggro: 6 },
  skeleton: { name: 'Esqueleto', hp: 60,  dmg: 11, speed: 70,  r: 10, faction: 'wild', drops: { bone: [1, 3] }, gold: [3, 12], xp: 22, aggro: 9 },
  spider:   { name: 'Aranha Gigante', hp: 45, dmg: 9, speed: 105, r: 11, faction: 'wild', drops: { spider_silk: [1, 2] }, xp: 18, aggro: 9 },
  bat:      { name: 'Morcego',   hp: 18,  dmg: 4,  speed: 130, r: 8,  faction: 'wild', drops: {}, xp: 6, aggro: 8 },
  troll:    { name: 'Troll das Cavernas', hp: 700, dmg: 26, speed: 72, r: 18, faction: 'wild', boss: true, drops: { ancient_coin: [4, 8] }, gold: [200, 350], xp: 400, aggro: 12 },
  skel_king:{ name: 'Rei Esqueleto', hp: 560, dmg: 22, speed: 80, r: 14, faction: 'wild', boss: true, drops: { ancient_coin: [5, 9], bone: [5, 8] }, gold: [250, 400], xp: 420, aggro: 12 },
  spider_queen: { name: 'Aranha Rainha', hp: 480, dmg: 20, speed: 95, r: 18, faction: 'wild', boss: true, drops: { spider_silk: [6, 10] }, gold: [180, 300], xp: 380, aggro: 12 },
  dragon:   { name: 'Dragão Ancestral', hp: 1200, dmg: 34, speed: 85, r: 24, faction: 'wild', boss: true, drops: { dragon_scale: [6, 9] }, gold: [600, 900], xp: 900, aggro: 14 },
  chicken:  { name: 'Galinha',   hp: 8,   dmg: 0,  speed: 50,  r: 6,  faction: 'pet', xp: 0 },
  cow:      { name: 'Vaca',      hp: 40,  dmg: 0,  speed: 30,  r: 13, faction: 'pet', xp: 0 },
  sheep:    { name: 'Ovelha',    hp: 25,  dmg: 0,  speed: 35,  r: 10, faction: 'pet', xp: 0 },
  caravan:  { name: 'Caravana',  hp: 160, dmg: 0,  speed: 55,  r: 16, faction: 'civ', xp: 0 },
  ally:     { name: 'Soldado',  hp: 60,  dmg: 9,  speed: 125, r: 10, faction: 'player', xp: 0, aggro: 8 },
  sentry:   { name: 'Guarda',   hp: 60,  dmg: 9,  speed: 110, r: 10, faction: 'player', xp: 0, aggro: 9 }, // capanga de guarda na vila ou no castelo
};

// prod = produção diária com 150 habitantes
const CIV_DEFS = [
  { name: 'Reino de Valdória',     short: 'Valdória', ruler: 'Rei Aldric',           color: '#2f6fd6', roof: '#34558f', title: ['Rei', 'Rainha'], rname: 'Aldric', rsex: 'm',
    prod: { wheat: 34, wood: 14, stone: 8, iron_ore: 3 }, desc: 'Planícies férteis e cavaleiros orgulhosos.' },
  { name: 'Império de Karthum',    short: 'Karthum',  ruler: 'Imperatriz Seraphine', color: '#c8322f', roof: '#8e2f2b', title: ['Imperador', 'Imperatriz'], rname: 'Seraphine', rsex: 'f',
    prod: { wheat: 24, wood: 8, stone: 18, iron_ore: 7 }, desc: 'Pedreiros e legiões disciplinadas.' },
  { name: 'Clã de Nordheim',       short: 'Nordheim', ruler: 'Jarl Bjorn',           color: '#3fb7c9', roof: '#2f6e7a', title: ['Jarl', 'Jarl'], rname: 'Bjorn', rsex: 'm',
    prod: { wheat: 22, wood: 18, stone: 8, iron_ore: 8 }, desc: 'Guerreiros das terras geladas do norte.' },
  { name: 'Principado de Elvaren', short: 'Elvaren',  ruler: 'Príncipe Lorien',      color: '#3fae4a', roof: '#2d6e33', title: ['Príncipe Regente', 'Princesa Regente'], rname: 'Lorien', rsex: 'm',
    prod: { wheat: 30, wood: 22, stone: 4, iron_ore: 2 }, desc: 'Guardiões das florestas antigas.' },
  { name: 'Domínio de Mordrak',    short: 'Mordrak',  ruler: 'Senhor Malgrave',      color: '#8e44c4', roof: '#5b2d80', title: ['Senhor', 'Senhora'], rname: 'Malgrave', rsex: 'm',
    prod: { wheat: 20, wood: 8, stone: 14, iron_ore: 12 }, desc: 'Mineiros sombrios das colinas.' },
  { name: 'Ducado de Brennor',     short: 'Brennor',  ruler: 'Duque Edmund',         color: '#e08a2a', roof: '#9a5a22', title: ['Duque', 'Duquesa'], rname: 'Edmund', rsex: 'm',
    prod: { wheat: 28, wood: 12, stone: 10, iron_ore: 5 }, desc: 'Mercadores ricos e portos movimentados.' },
  { name: 'Marca de Valtaris',     short: 'Valtaris', ruler: 'Marquesa Isolde',      color: '#d14f9a', roof: '#8a2f62', title: ['Marquês', 'Marquesa'], rname: 'Isolde', rsex: 'f',
    prod: { wheat: 26, wood: 16, stone: 9, iron_ore: 6 }, desc: 'Arqueiros das colinas e vinhedos sem fim.' },
];

const KINGDOM_RES = ['wheat', 'wood', 'stone', 'iron_ore'];

// peso dos itens (a mochila tem limite; cavalo e carroça aumentam a carga)
const CAT_WEIGHT = { Recursos: 1, Materiais: 1.5, Comida: 0.3, Ferramentas: 3, Armas: 4, Armaduras: 5, Diversos: 0.5 };
const WEIGHT_OVERRIDE = { stone: 1.5, iron_ore: 1.5, copper_ore: 1.5, tin_ore: 1.5, silver_ore: 1, gold_ore: 0.5, gem: 0.3, arrow: 0.05, iron_arrow: 0.08,
  boat: 0, fiber: 0.2, herb: 0.2, ancient_coin: 0.1, silver_ring: 0.1, berries: 0.2 };
function itemWeight(k) { return WEIGHT_OVERRIDE[k] !== undefined ? WEIGHT_OVERRIDE[k] : (CAT_WEIGHT[ITEMS[k].cat] || 1); }
const BASE_CARRY = 220, HORSE_CARRY = 120, CART_CARRY = 450;
// níveis da mochila: carga e materiais para melhorar (feito na bancada)
const BAG_LEVELS = [
  { cap: 220, name: 'Saco de Pano' },
  { cap: 251, name: 'Bornal de Couro',      cost: { leather: 4, rope: 2 } },
  { cap: 282, name: 'Mochila de Couro',     cost: { leather: 6, rope: 3, cloth: 2 } },
  { cap: 313, name: 'Mochila Reforçada',    cost: { leather: 8, cloth: 4, rope: 4 } },
  { cap: 344, name: 'Mochila de Viajante',  cost: { leather: 10, cloth: 6, wolf_pelt: 1 } },
  { cap: 376, name: 'Mochila de Caçador',   cost: { leather: 12, cloth: 8, wolf_pelt: 2, iron_bar: 2 } },
  { cap: 407, name: 'Mochila de Lã Grossa', cost: { leather: 15, wool: 10, wolf_pelt: 3, iron_bar: 4 } },
  { cap: 438, name: 'Mochila de Mercador',  cost: { leather: 18, wool: 12, silk_cloth: 2, iron_bar: 6 } },
  { cap: 469, name: 'Mochila de Expedição', cost: { leather: 22, wolf_pelt: 5, silk_cloth: 4, steel_bar: 3 } },
  { cap: 500, name: 'Mochila Lendária',     cost: { leather: 26, wolf_pelt: 6, silk_cloth: 6, steel_bar: 6, gem: 1 } },
];
// efeitos temporários de comidas e bebidas (duração em segundos reais)
const BUFFS = {
  str:     { name: 'Força',       icon: '💪', dur: 180, desc: '+20% de dano' },
  def:     { name: 'Resistência', icon: '🛡️', dur: 180, desc: '+4 de defesa' },
  vigor:   { name: 'Vigor',       icon: '⚡', dur: 180, desc: 'energia recupera 2× mais rápido' },
  regen:   { name: 'Saúde',       icon: '❤️', dur: 180, desc: 'vida recupera 3× mais rápido' },
  wisdom:  { name: 'Sabedoria',   icon: '📖', dur: 240, desc: '+30% de experiência' },
  courage: { name: 'Coragem',     icon: '🍺', dur: 240, desc: '+15% de dano' },
  mead:    { name: 'Hidromel',    icon: '🍶', dur: 240, desc: 'vida recupera 2× e +10% de velocidade' },
  blessed: { name: 'Bênção',     icon: '🙏', dur: 180, desc: 'vida recupera 2× e +2 de defesa' },
  holy:    { name: 'Graça Divina', icon: '✨', dur: 360, desc: '+15% de dano e +3 de defesa' },
  charm:   { name: 'Charme',      icon: '🍷', dur: 300, desc: 'preços 10% melhores e conversas mais agradáveis' },
};
const CROPS = {
  wheat:   { name: 'Trigo',   seed: 'wheat_seed',   item: 'wheat',   days: 3, yield: [3, 5], color: '#d8b84a' },
  carrot:  { name: 'Cenoura', seed: 'carrot_seed',  item: 'carrot',  days: 2, yield: [2, 4], color: '#e8742a' },
  cabbage: { name: 'Repolho', seed: 'cabbage_seed', item: 'cabbage', days: 3, yield: [1, 3], color: '#7ac04a' },
  barley:  { name: 'Cevada',  seed: 'barley_seed',  item: 'barley',  days: 3, yield: [3, 5], color: '#c8c86a' },
};
const ANIMAL_PRICES = { chicken: 15, cow: 120, sheep: 60 };
const DIFFICULTY = {
  easy:   { name: 'Fácil',   dmg: 0.6, hp: 0.8, hunger: 0.7, gameover: false, sell: 1.2, desc: 'Inimigos mais fracos; ao morrer você volta para casa e perde só parte do ouro.' },
  normal: { name: 'Normal',  dmg: 1,   hp: 1,   hunger: 1,   gameover: true,  sell: 1,   desc: 'A experiência pensada para o jogo. Morrer é fim de jogo (continue como seu filho).' },
  hard:   { name: 'Difícil', dmg: 1.4, hp: 1.3, hunger: 1.3, gameover: true,  sell: 0.9, desc: 'Inimigos fortes, mais fome e preços piores. Para veteranos.' },
};
const SEASONS = [
  { name: 'Primavera', icon: '🌸', wheat: 1.0, farm: 6 },
  { name: 'Verão',     icon: '☀️', wheat: 1.2, farm: 8 },
  { name: 'Outono',    icon: '🍂', wheat: 1.4, farm: 10 },
  { name: 'Inverno',   icon: '❄️', wheat: 0.35, farm: 0 },
];

const INVESTMENTS = {
  farms:   { name: 'Fazendas Reais',  icon: '🌾', desc: '+25% de trigo',                 cost: { gold: 150, wood: 30 },             res: 'wheat' },
  sawmill: { name: 'Serrarias',       icon: '🪵', desc: '+25% de madeira',               cost: { gold: 100, stone: 10 },            res: 'wood' },
  quarry:  { name: 'Pedreiras',       icon: '🪨', desc: '+25% de pedra',                 cost: { gold: 120, wood: 20 },             res: 'stone' },
  mines:   { name: 'Minas de Ferro',  icon: '⛏️', desc: '+25% de minério de ferro',      cost: { gold: 200, wood: 30, stone: 20 },  res: 'iron_ore' },
  housing: { name: 'Moradias',        icon: '🏘️', desc: '+40 de capacidade populacional', cost: { gold: 150, wood: 40, stone: 20 } },
  walls:   { name: 'Muralhas',        icon: '🏰', desc: '+6 de guarnição máxima',        cost: { gold: 300, stone: 80 } },
};

const VILLAGE_NAMES = ['Pedravale', 'Vau do Corvo', 'Moinho Velho', 'Ribeirão', 'Altamira', 'Fonte Fria',
  'Carvalhal', 'Lago Prata', 'Monte Sombrio', 'Vila Ferro', 'Campo Dourado', 'Bruma Alta', 'Porto Salgado', 'Vinhal',
  'Rochedo', 'Três Pontes', 'Ermida', 'Valverde', 'Torre Velha', 'Freixial', 'Sombreiro', 'Penha Negra', 'Águas Claras', 'Lobeira']; 

const RUMORS = [
  'Dizem que veios de ouro e prata brilham nas colinas perto das montanhas... mas só uma picareta de ferro os quebra.',
  'Bandidos montaram acampamentos nas terras selvagens. Quem os expulsa ganha o respeito de todos os reinos.',
  'Um soberano só cai quando toda a sua guarnição é derrotada. Leve soldados com você!',
  'Os reis respeitam quem faz negócios com eles. Venda em seus mercados e a relação melhora.',
  'Com relação alta e 1500 moedas, um soberano pode até ceder o trono sem derramar sangue.',
  'À noite os lobos ficam mais ousados. Uma fogueira acesa ajuda a enxergar.',
  'O bronze nasce do cobre e do estanho, fundidos com carvão. Com uma picareta de bronze já se quebra o ferro.',
  'Impostos altos enchem o tesouro, mas o povo infeliz pode se rebelar.',
  'Carne e peixe assados curam muito mais do que crus. Construa uma fogueira!',
  'Pescadores dizem que o bacalhau só morde em mar aberto. Arrume um barco!',
  'Nas ilhas do sul há riquezas que nenhum rei reclamou. Só se chega lá de barco.',
  'O Carvalho Ancião das florestas profundas dá a madeira mais nobre... se você tiver um machado de ferro.',
  'Gemas brutas escondem-se entre as rochas das terras altas. Só o aço consegue arrancá-las.',
  'A argila das margens dos rios vira tijolo na forja. Tijolos erguem casarões!',
];

const REBEL_NAMES = ['Gorm, o Rebelde', 'Lady Vesna', 'Capitão Darrow', 'Irmão Caius', 'Varga, a Ruiva'];
